apiVersion: v1
kind: ConfigMap
metadata:
  namespace: anotherclass-123
  name: api-tester-1231-properties
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-1231
    managed-by: kubectl
data:
  spring-profiles-active: "dev"
  application-role: "ALL"
  postgresql-file-path: "/usr/src/myapp/datasource/postgresql-info.yaml"