apiVersion: v1
kind: ConfigMap
metadata:
  namespace: anotherclass-123
  name: api-tester-1231-properties
  labels:
    k8s.another.class/part-of: k8s-anotherclass
    k8s.another.class/component: backend-server
    k8s.another.class/name: api-tester
    k8s.another.class/instance: api-tester-1231
    k8s.another.class/managed-by: kubectl
data:
  spring-profiles-active: "dev"
  application-role: "ALL"
  postgresql-file-path: "/usr/src/myapp/datasource/postgresql-info.yaml"