apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-123
  name: api-tester-1231
  labels:
    k8s.another.class/part-of: k8s-anotherclass
    k8s.another.class/component: backend-server
    k8s.another.class/name: api-tester
    k8s.another.class/instance: api-tester-1231
    k8s.another.class/version: 1.0.0
    k8s.another.class/managed-by: kubectl
spec:
  selector:
    matchLabels:
      k8s.another.class/part-of: k8s-anotherclass
      k8s.another.class/component: backend-server
      k8s.another.class/name: api-tester
      k8s.another.class/instance: api-tester-1231
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.another.class/part-of: k8s-anotherclass
        k8s.another.class/component: backend-server
        k8s.another.class/name: api-tester
        k8s.another.class/instance: api-tester-1231
        k8s.another.class/version: 1.0.0
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: api-tester-1231
          image: 1pro/api-tester:v1.0.0
          envFrom:
            - configMapRef:
                name: api-tester-1231-properties
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 2
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - name: files
              mountPath: /usr/src/myapp/dev/files
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: api-tester-1231-files
        - name: secret-datasource
          secret:
            secretName: api-tester-1231-postgresql