apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-123
  name: api-tester-1231
  labels:
    app.kubernetes.io/part-of: k8s-anotherclass
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: api-tester-1231
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/part-of: k8s-anotherclass
      app.kubernetes.io/component: backend-server
      app.kubernetes.io/name: api-tester
      app.kubernetes.io/instance: api-tester-1231
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: k8s-anotherclass
        app.kubernetes.io/component: backend-server
        app.kubernetes.io/name: api-tester
        app.kubernetes.io/instance: api-tester-1231
        app.kubernetes.io/version: 1.0.0
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: api-tester-1231
          image: 1pro/api-tester:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-tester-1231-properties
          startupProbe:
            httpGet:
              path: "/startup"
              port: http
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: http
            periodSeconds: 10
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: http
            periodSeconds: 10
            failureThreshold: 2
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      volumeMounts:
        - name: files
          mountPath: /usr/src/myapp/dev/files
        - name: secret-datasource
          mountPath: /usr/src/myapp/datasource
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: api-tester-1231-files
        - name: secret-datasource
          secret:
            secretName: api-tester-1231-postgresql