apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: 1-2-3-1
  name: api-tester-default
  labels:
    app.kubernetes.io/part-of: anotherclass-simple-app
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: "1-2-3-1"
    app.kubernetes.io/version: "1.0.0"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-tester
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 100