apiVersion: v1
kind: PersistentVolume
metadata:
  name: anotherclass-123-api-tester-1231-files
  labels:
    k8s.another.class/part-of: k8s-anotherclass
    k8s.another.class/component: backend-server
    k8s.another.class/name: api-tester
    k8s.another.class/instance: api-tester-1231-files
    k8s.another.class/managed-by: kubectl
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: "/root/k8s-local-volume/1231"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In, values: [k8s-master]}