apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: 1-2-3-1
  name: api-tester-files
  labels:
    app.kubernetes.io/part-of: anotherclass-simple-app
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: "1-2-3-1"
    app.kubernetes.io/version: "1.0.0"
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/part-of: anotherclass-simple-app
      app.kubernetes.io/component: backend-server
      app.kubernetes.io/name: api-tester
      app.kubernetes.io/instance: "1-2-3-1"
      app.kubernetes.io/version: "1.0.0"