apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: anotherclass-1231
  name: api-tester-1231-files
  labels:
    app.kubernetes.io/part-of: k8s-anotherclass
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: api-tester-1231
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: kubectl
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/part-of: k8s-anotherclass
      app.kubernetes.io/component: backend-server
      app.kubernetes.io/name: api-tester
      app.kubernetes.io/instance: api-tester-1231