apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-1231
  name: api-tester
  labels:
    app.kubernetes.io/part-of: k8s-anotherclass
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: api-tester-1231
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app.kubernetes.io/part-of: k8s-anotherclass
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: api-tester-1231
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31231
  type: NodePort