apiVersion: v1
kind: Service
metadata:
  namespace: 1-2-3-1
  name: api-tester
  labels:
    app.kubernetes.io/part-of: anotherclass-simple-app
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: "1-2-3-1"
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app.kubernetes.io/part-of: anotherclass-simple-app
    app.kubernetes.io/component: backend-server
    app.kubernetes.io/name: api-tester
    app.kubernetes.io/instance: "1-2-3-1"
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31231
  type: NodePort