apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-221
  name: api-tester-2214-green
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2214-green
    version: 2.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2214-green
  ports:
    - port: 80
      targetPort: http
      nodePort: 32224
  type: NodePort